sudo: required
services:
  - docker

language: ruby

rvm:
  - "2.3.7"

install:
  - docker-compose -f ./.travis/docker-compose-travis.yml up -d

script:
  - docker exec forum_testing /edx/app/forum/cs_comments_service/.travis/run_tests.sh
